config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :artists, :suggestions

  devise_for :admins
  get 'profiles/show'

  devise_for :users, :controllers => { :registrations => 'registrations'}
  devise_scope :user do
    get "register", to: 'devise/registrations#new', as: :register
    get "login", to: 'devise/sessions#new', as: :login
    get "logout", to: 'devise/sessions#destroy', as: :logout
  end

  resources :posts do
    member do
      get 'like'
    end
  end
  get "feed", to: 'posts#index', as: :feed
  get "moderate", to: 'posts#moderate', as: :moderate
  get "create", to: 'posts#new', as: :create_post
  put '/posts/:id/publish' => 'posts#publish_post', :as => 'publish_post'
  put '/posts/:id/acceptsug' => 'posts#accept_suggestion', :as => 'accept_suggestion'
  root to: 'posts#index'

  delete 'decline_suggestion' => 'suggestions#destroy'

  get '/:id', to: 'profiles#show', as: :profile

end

app/models/post.rb
class Post < ActiveRecord::Base
	make_flaggable
	has_attached_file :picture,
						:convert_options => { :all => "-quality 75" },
						:styles => { :small => "278x" },
						:url => "/assets/posts/:id/:style/:basename.:extension",
						:path => ":rails_root/public/assets/posts/:id/:style/:basename.:extension"

	validates_attachment :picture, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }, size: { less_than: 5.megabytes }
	validates :picture, presence: true
	validates :location, presence: true
	validates :city, presence: true
	validates :user_id, presence: true

	geocoded_by :full_address do |obj,results|
	  if geo = results.first
	    obj.country = geo.country
	    obj.city = geo.city
	    obj.latitude = geo.latitude
	    obj.longitude = geo.longitude
	  end
	end


	belongs_to :user
	belongs_to :artist
	has_many :suggestions

	after_validation :geocode, :if => Proc.new { latitude.blank? }

	scope :approved, -> { where(approved: true) }
	scope :not_approved, -> { where(approved: false) }



	def full_address
    	location + ", " + city
   	end

   	def likes
   		flaggings_count.to_s
   	end

   	private

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:moderate, :new, :create, :edit, :update]
  before_filter :authorize_admin, only: [:moderate, :edit, :update, :destroy, :publish_post]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  

  def like
    @post = Post.find(params[:id])

    if current_user.flagged?(@post)
      current_user.unflag(@post)
      redirect_to posts_path, :notice => "You now dislike this post"   
    else
      current_user.flag(@post, :like)
      redirect_to posts_path, :notice => "You now like this post"   
    end
  end

  # GET /posts
  # GET /posts.json
  def index
    if params[:sort]
      @posts = Post.approved.order(params[:sort])
    else
      @posts = Post.approved.order("created_at DESC")
    end
  end

  # GET /moderate
  def moderate
    @posts = Post.not_approved.order("created_at DESC")
    @suggestions = Suggestion.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    if @post.approved? || current_user.admin?
      return
    else
      redirect_to root_url
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end


  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if current_user.admin?
      @post.approved = true
    end

    respond_to do |format|
      if @post.save
        if current_user.admin?
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
        else
          format.html { redirect_to @post, notice: 'Great! Your post will be moderated soon!' }
        end
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
    if (@post.approved?)
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    else
       format.html { redirect_to moderate_url, notice: 'Post was successfully destroyed.' }
    end
      format.json { head :no_content }
    end
  end


  def publish_post
      @post = Post.find(params[:id])
      @post.update_attribute(:approved, true)
      redirect_to moderate_url, :notice => "Post published!"
  end

  def accept_suggestion
      @suggestion = Suggestion.find(params[:id])
      @user = @suggestion.user
      @post = @suggestion.post
      @user.increment!(:suggested, by = 1)
      @post.update_attribute(:artist_id, @suggestion.artist_id)
      @suggestion.destroy
      redirect_to :back, :notice => "Suggestion accepted!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:location, :city, :country, :picture, :user_id, :artist_id, :approved, :latitude, :longitude)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

	def toggle_like_button(post, user)
		if user.flagged?(post)
			link_to "Unlike", like_post_path(post)
		else
			link_to "Like", like_post_path(post)
		end
	end

	def likes_plural(post)
		if post.flaggings.count == 0
			""
		elsif post.flaggings.count == 1
			post.likes + " Like - "
		else
			post.likes + " Likes - "
		end
	end

end

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :picture %>
    <%= f.input :artist_id, collection: Artist.all, label_method: :name %>
    <%= f.input :location, :input_html => { :id => "geo-location" } %>
    <%= f.input :city, :input_html => { :id => "geo-city" } %><br/>
    <div id="GPSLocation-box" style="display:none;">
      <input type="button" onclick="get_location()" value="Locate Me" /><br/><br/>
      <%= f.input :latitude, :input_html => { :id => "geo-latitude" } %>
      <%= f.input :longitude, :input_html => { :id => "geo-longitude" } %>
      <%= f.input :country, :input_html => { :id => "geo-country" } %>
      <div id="geoinfo"></div>
    </div>
    <script language="javascript" type="text/javascript"> 
      if (navigator.geolocation) {  
        $( "#GPSLocation-box" ).show();
      } else {  
          
      }

      function get_location(){
        navigator.geolocation.getCurrentPosition(geocode, handle_error,  {enableHighAccuracy:true,maximumAge:600000});
      }

        function geocode(position)
        {
          var latlong = position.coords.latitude + "," + position.coords.longitude;

          if(window.XMLHttpRequest)
            var request = new XMLHttpRequest();
          else if(window.ActiveXObject)
            var request = ActiveXObject("Microsoft.XMLHTTP");

          request.open("GET", "http://maps.googleapis.com/maps/api/geocode/json?latlng=" + latlong + "&sensor=true&language=en", true);
          request.send();

          request.onreadystatechange = function()
          {
            if(request.readyState == 4 && request.status == 200)
            {
              var address = eval("(" + request.responseText + ")");
              document.getElementById("geo-location").value = address.results[0].address_components[0].long_name + " " + address.results[0].address_components[1].long_name;
              document.getElementById("geo-city").value = address.results[5].address_components[0].long_name;
              document.getElementById("geo-country").value = address.results[9].address_components[0].long_name;
              document.getElementById("geo-latitude").value = position.coords.latitude;
              document.getElementById("geo-longitude").value = position.coords.longitude;
            }
          }
        }

        function handle_error(err)
        {
          switch(err.code)
          {
            case 1: /* PERMISSION_DENIED */ break;
            case 2: /* POSITION_UNAVAILABLE */ break;
            case 3: /* TIMEOUT */ break;
          }
          alert(err.code);
        }


    </script>


    <%= f.button :submit %>
<% end %>

   

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post post-masonry">
        <%= link_to image_tag(post.picture.url(:small)), post %>
        <div class="post-details">
          <h4 class="post-address"><%= link_to post.location, post %></h4>
          <h5 class="post-city"><%= link_to post.city + ", " + post.country, post %></h5>
          <div class="post-more">
            <hr>
            <span>Uploaded by <%= link_to post.user.profile_name, profile_path(post.user.profile_name) %> <%= time_ago_in_words(post.created_at) + " ago" %></span>
            <span><%= likes_plural(post) %><% if current_user.present? %><%= toggle_like_button(post, current_user) %><% end %>
              <% if current_user && current_user.admin? %> |  <%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></span>
          </div>
        </div>

      </div>
  <% end %>

app/views/posts/index.js.erb
alert("it works")
$('#posts-container').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/moderate.html.erb
    <ul>
    <% @suggestions.each do |suggestion| %>
      <li><%= suggestion.user.profile_name %> suggested "<%= suggestion.artist.name %>" for <%= link_to suggestion.post.location, suggestion.post %><br/>
        <%= link_to 'Accept', accept_suggestion_path(suggestion.id), :method => :put %>
         | <%= link_to 'Decline', decline_suggestion_path(:id => suggestion.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
    </ul>
    <% @posts.each do |post| %>
<div class="post">
        <%= link_to image_tag(post.picture.url(:small)), post %>
        <div class="post-details">
          <h4 class="post-address"><%= link_to post.location, post %></h4>
          <h5 class="post-city"><%= link_to post.city + ", " + post.country, post %></h5>
          <div class="post-more">
            <hr>
            <span>Uploaded by <%= link_to post.user.profile_name, profile_path(post.user.profile_name) %> <%= time_ago_in_words(post.created_at) + " ago" %></span>
            <span><%= link_to 'Publish', publish_post_path(post.id), :method => :put %> | <%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </div>
        </div>

      </div>

        <% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
      <%= link_to 'Back to the list', posts_path %><br/><br/>

<div class="post">
        <%= image_tag(@post.picture.url(:small)) %>
        <div class="post-details">
          <h4 class="post-address"><%= @post.location %></h4>
          <h5 class="post-city"><%= @post.city + ", " + @post.country %></h5>
          <div class="post-more">
            <hr>
            <span>Uploaded by <%= link_to @post.user.profile_name, profile_path(@post.user.profile_name) %> <%= time_ago_in_words(@post.created_at) + " ago" %></span>
            <span><% if current_user.present? %><%= link_to "Like", like_post_path(@post) %><% end %><% if current_user && current_user.admin? %> |  <%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></span>
          </div>
        </div> 

      </div>
      <% if @post.artist.blank? %>
        Do you know the artist?
        <%= render partial: "suggestions/form", locals: {suggestion: Suggestion.new, post: @post} %>
      <% end %>
      <%= image_tag "http://maps.google.com/maps/api/staticmap?size=360x200&sensor=false&zoom=16&markers=#{@post.latitude}%2C#{@post.longitude}" %>  