config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :artists, :suggestions

  devise_for :admins
  get 'profiles/show'

  devise_for :users, :controllers => { :registrations => 'registrations'}
  devise_scope :user do
    get "register", to: 'devise/registrations#new', as: :register
    get "login", to: 'devise/sessions#new', as: :login
    get "logout", to: 'devise/sessions#destroy', as: :logout
  end

  resources :posts do
    member do
      get 'like'
    end
  end
  get "feed", to: 'posts#index', as: :feed
  get "moderate", to: 'posts#moderate', as: :moderate
  get "create", to: 'posts#new', as: :create_post
  put '/posts/:id/publish' => 'posts#publish_post', :as => 'publish_post'
  put '/posts/:id/acceptsug' => 'posts#accept_suggestion', :as => 'accept_suggestion'
  root to: 'posts#index'

  delete 'decline_suggestion' => 'suggestions#destroy'

  get '/:id', to: 'profiles#show', as: :profile

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drips</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic,700italic|Raleway:400,700,600,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
		<div id="header-container">
			<h1>Drips</h1>
			<%= link_to 'New Post', create_post_path, class: "btn newpost" %>
		</div>
	</div>

	<div id="page-container">
		<% if user_signed_in? %>
		Hello <%= link_to current_user.profile_name, profile_path(current_user.profile_name) %>
			<% if current_user.admin? %>
				 | <%= link_to "Moderate", moderate_path %>
			<% end %>
			 | <%= link_to "Log Out", logout_path%><br>
		<% else %>
			<%= link_to "Register", register_path %> | <%= link_to "Log In", login_path %><br>
		<% end %>

		<% flash.each do |type, message| %>
			<p class="<%= type %>"><%= message %></p>
		<% end %>
		<%= link_to "Recent", :sort => "created_at DESC" %> |  
		<%= link_to "Popular", :sort => "flaggings_count DESC" %><br><br>
		<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix centered">
			<%= yield %>
		</div>
	</div>



</body>
</html>